### ISSUE TITLE
[Enhancement] 폰트 선명도 개선 요청

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/Report#10]
PDF 파일로 렌더링 했을 때 글씨가 모두 동일한 선명도가 되면 좋겠습니다.
PDF 파일을 볼 때 일부러 저 부분만 집중적으로 확대하지 않더라도 (사진은 800%)
제 모니터 기준 200% 정도는 키워야 보기 편합니다. 
200% 정도로 볼때도 선명도가 낮은 글씨는 뭉개져 보입니다.

![개선1](https://user-images.githubusercontent.com/8017454/126754259-50d355ea-dc1d-431b-af56-8493fe08b1d9.png)

**Comment by KimYC1223** [comment]
저는... 다른 내용이긴 한데,

폰트가 깨지는 현상은 없습니다. #11 에서와 같이,

크롬에서 작업하고 "PDF로 저장"옵션을 선택했으며, PDF 뷰어는 크롬 브라우저를 사용했습니다.

(확대 배율은 500%입니다)

![image](https://user-images.githubusercontent.com/40852277/126758760-c4201a70-9c16-4864-8424-6a440c6d266a.png)

대신 저는... 한글 텍스트가 안보이네요.

레포트 대상은 김성실입니다.

**Comment by junhyungmoon** [comment]
수고하셨습니다
