### ISSUE TITLE
[Enhancement] 데이터 라벨 모양 변경 요청

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/Report#11]
지난번 이경우,이현경 교수님께서 요청하셨던 것을 남겨둡니다.
라벨 모양을 깔끔하게 바꾸는 것이 낫겠다고 하셨습니다.

![개선1](https://user-images.githubusercontent.com/8017454/126754401-05c6ff9c-8852-4c83-ad7d-909b24b31448.png)

**Comment by junhyungmoon** [comment]
여기도 보면 1. 은 글씨가 깨지고 수분 섭취는 안깨지네요...

**Comment by KimYC1223** [comment]
이슈 중에서 "1." 글자가 깨지는 현상은,

제 PDF에서는 일어나지 않습니다.

![image](https://user-images.githubusercontent.com/40852277/126758328-ea5fd37e-e053-4f44-8113-303a662e2c81.png)

심지어 데이터 라벨 이미지도 깨지지 않네요.

혹시 이 내용도 #12 에서처럼 Adobe pdf 변환기를 사용해서 변환하신건가요?

---

저는 **크롬 환경**에서 **"PDF로 저장"** 옵션을 선택했고,

PDF뷰어도 **크롬 브라우저**를 사용하고 있습니다.

---

그리고, 라벨 이미지는 png 이미지라서 많이 확대하면 충분히 깨질 수 있지만,

"1." 의 경우 일반 텍스트인데 저렇게 화질이 좋지 않아 보이는건 저도 이해가 잘 안가네요.

인쇄 설정을 어떤걸로 하셨는지 궁금합니다!

**Comment by junhyungmoon** [comment]
영찬학생 말대로 PDF로 저장 옵션으로 렌더링 하니 깨지지 않습니다.
다만, 라벨 모양 변경 요청은 지난 회의에서 두 교수님께서 모양을 변경하는게 더 깔끔해 보인다고 말씀하신 것입니다. 선명도 문제와 별개입니다.

**Comment by junhyungmoon** [comment]
@KimYC1223 @sayiovme 
이경우교수님께서 지속적으로 말씀하시는 사항입니다 "일별 데이터" 앞의 도형 깔끔하게 단색 동그라미나 네모로 바꾸기로 했습니다. (모든 페이지 동일)

**Comment by sayiovme** [comment]
![image](https://user-images.githubusercontent.com/60974691/128024938-de285fe1-1209-4a70-8dae-35273c357a5d.png)

우선 단색 동그라미로 제가 바꿔두었습니다.

*서버 반영 이후 메일 발송 예정
