### ISSUE TITLE
[Enhancement] PDF 파일 최하단에 표기되는 링크 삭제 요청

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/Report#12]
최하단에 드러나는 링크를 지우면 더 완성도가 높아보이겠습니다.

![개선1](https://user-images.githubusercontent.com/8017454/126754750-3fe8fceb-b1fd-4187-b901-e5a29d6da034.png)

**Comment by junhyungmoon** [comment]
마찬가지로 최상단의 날짜와 FluidTrack Report 라고 작게 나오는 것도 삭제하면 좋겠습니다

**Comment by KimYC1223** [comment]
제가 만든 PDF에는 해당 내용이 없는데... 어떤 방법으로 인쇄하신건지 말씀해주시면 알아보겠습니다.

[FluidTrack Report2.pdf](https://github.com/FluidTrack/Report/files/6867439/FluidTrack.Report2.pdf)

자세한 내용은 #9 코멘트에 적어두었습니다.

**Comment by junhyungmoon** [comment]
사이트 내에 보이는 PDF 변환 버튼 눌러서 바로 저장 눌렀습니다. 다른 옵션은 건드리지 않았습니다

**Comment by junhyungmoon** [comment]
지금보니 제 데스크탑에서는 "Adobe PDF" 옵션이 default 로 되어있는데, 그렇게 저장하면 위의 이슈와 다른 몇가지 이슈가 모두 나타나는 것 같습니다. "PDF로 저장" 옵션을 하면 영찬학생처럼 출력됩니다

**Comment by KimYC1223** [comment]
PDF의 설정 방법은 하단의 버튼들 중

![image](https://user-images.githubusercontent.com/40852277/126755618-e4da52fb-0bdc-4973-bad6-01f78a770889.png)

주의사항에 적어두었습니다!
