### ISSUE TITLE
[Enhancement] 소숫점 제한 요청

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/Report#13]
지난 회의에서 이경우교수님께서 말씀하셨던 소수점 이슈입니다. 
2자리는 일반 부모가 이해하기 너무 디테일한 것 같고 소숫점을 없애거나 1자리 정도가 적당할 것 같습니다
![개선1](https://user-images.githubusercontent.com/8017454/126755565-f0f0b002-2fba-4348-8c07-6a635b4cb07e.png)

**Comment by sayiovme** [comment]
완료하였습니다.

![image](https://user-images.githubusercontent.com/60974691/126852448-0c91b4e1-23ea-42b4-9afb-96776f3dfbaa.png)

**Comment by junhyungmoon** [comment]
황선영_심함, 7,8주 데이터 렌더링 시 배뇨 페이지 쪽에 소숫점 두자리가 아직 남아있습니다

**Comment by junhyungmoon** [comment]
시간대별 평균 데이터(배뇨) 에도 남아있습니다.

**Comment by sayiovme** [comment]
수정한 것이 아직 서버에 올라가지 않은 것으로 보입니다.
Timezone graph는 수정 완료하였습니다.
TImezone graph의 Tooltip은 캡처할 수가 없네요 ㅜㅜ 
*이후 서버 반영 예정

![image](https://user-images.githubusercontent.com/60974691/127241972-0facba17-655d-4f3d-b0fc-2992cb134a18.png)
