### ISSUE TITLE
[Enhancement] 대변 Y축 최대값 수정 요청

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/Report#14]
지난 회의 이경우교수님 코멘트입니다.
Y축 최대값을 3을 default 로 잡아주세요

![개선2](https://user-images.githubusercontent.com/8017454/126755673-f475e3f0-9466-46c3-91b4-1d4b0f242206.png)

**Comment by sayiovme** [comment]
완료하였습니다.

![image](https://user-images.githubusercontent.com/60974691/126852534-a3915849-e14a-46ab-a2ec-c96f5bfe076a.png)

**Comment by junhyungmoon** [comment]
y축 최대가 2로 보입니다

![화면 캡처 2021-07-27 144220](https://user-images.githubusercontent.com/8017454/127102054-57472f96-5789-4953-a272-2037e7258a25.png)

**Comment by sayiovme** [comment]
![image](https://user-images.githubusercontent.com/60974691/127242065-a55872c1-3b9f-4067-bb43-1b7764f92dd9.png)

이것도 Git에서 충돌이 있었던 것 같습니다.
수정 완료하였습니다.

*이후 서버 반영 예정
