### ISSUE TITLE
[Enhancement] 사이트와 PDF 모두에서 그래프 내 선 표시 개선 요청

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/Report#15]
빨간 동그라미 친 부분들이 서로 다른 선처럼 보입니다.
예를 들어 12 바로 옆에 검정색 진한 선이 있고 그 위에 회색 선이 덧칠해진 것처럼 보입니다.
일반적인 그래프처럼 같은 하나의 선으로 보이도록 개선해 주세요

![개선3](https://user-images.githubusercontent.com/8017454/126755824-c2980678-2df9-49ba-a634-484ca3137c84.png)

**Comment by sayiovme** [comment]
tick을 없애고, opacity를 조절하여 해결하였습니다.

![image](https://user-images.githubusercontent.com/60974691/127254185-3a1014c4-e456-46bd-9177-12c331c0b6c5.png)
