### ISSUE TITLE
[Enhancement] 사이트 내에서 배율 확대시 하단 메뉴 크기 조절 요청

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/Report#16]
제가 캡처하면서 확대한 배율이 저에겐 과도한 수준은 아니고 저정도로 확대할만한 데이터입니다.
이슈로 등록하고자 일부러 확대했다는 것이 아니라는 말씀을 드리는 것입니다.
더군다나 이 것을 사용하시는 분들은 저보다도 연세가 있으시므로 더 확대할 수도 있습니다.
저희 교수님께서 매번 작아서 잘 안보이니 확대해달라고 하시기도 하죠
확대를 할 수록 버튼이 너무 커져서 리포트가 가려지는데 이 것을 개선하면 좋겠습니다

![개선3](https://user-images.githubusercontent.com/8017454/126756263-d0219923-885b-4a19-96d8-82ee1a9b36a0.png)

**Comment by KimYC1223** [comment]
이것은 제가 담당하고 있습니다.
확인 후 수정하겠습니다

**Comment by KimYC1223** [comment]
고정 비율이 아닌 화면의 viewport scale를 참고하여 동적으로 조정되도록 변경하였습니다.
