### ISSUE TITLE
[Enhancement] DB에 다양한 케이스의 데이터 입력 요청

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/Report#17]
지난 회의에서 이경우교수님께서 말씀하신 사항입니다.

본 연구에 참가할 아동은 주 4회 이상 기기를 사용하지 않으면 자동 탈락됩니다.
이 점을 염두하여 몇가지 사례들을 생성해주세요.

점점 증상이 나아지는 아이, 오히려 심해지는 아이, 
성실한 아이, 불성실한 아이(중도 탈락할 정도는 아닌) 등등

**Comment by sayiovme** [comment]
증상이 나아지는 아이(66번), 증상이 심해지는 아이(70번)은 데이터를 넣어두었습니다.
성실한 아이는 66번, 70번으로 파악 가능한 것으로 보입니다.
불성실한 아이 데이터 또한 넣어두겠습니다.
