### ISSUE TITLE
[BUG] 대변 이미지 깨짐 현상

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/Report#18]
김성실, 1~2주차 리포트입니다.

![화면 캡처 2021-07-27 144220](https://user-images.githubusercontent.com/8017454/127101743-d5ad30a6-8385-427e-9daf-4482486ec6a8.png)

**Comment by sayiovme** [comment]
Git pull/push 중 충돌 현상으로 일어난 bug로 보입니다.
픽스하였습니다.


*웹서버에는 이후 반영될 예정
