### ISSUE TITLE
[Enhancement] 상단 문구 수정 요청

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/Report#19]
영찬학생이 제 요청에 따라 수정해준 것은 확인했는데요 읽어보니 좀 적절하지 않은 것 같아서 수정하려고 합니다.

수정버전: "이 리포트는 2주간 모아밴드와 모아정원 어플리케이션을 통해 기록한 아동의 수분 섭취, 배뇨, 배변에 대한 상세한 설명을 제공할 목적으로 제작되었습니다."

![화면 캡처 2021-07-27 215659](https://user-images.githubusercontent.com/8017454/127158116-ae5a33fd-5cdc-4713-9d46-131d62589af7.png)

**Comment by junhyungmoon** [comment]
관련하여 최상단의 "모아밴드 기록 분석 리포트" 도 수정이 필요하겠습니다. 
엄밀히 말하면 모아밴드와 모아정원 App 모두를 통해 기록한 내용이기 때문입니다.

"수분 섭취, 배뇨, 배변 기록 분석 리포트" 로 변경 부탁합니다. 글씨 크기는 살짝 줄여도 좋을것 같습니다.

**Comment by KimYC1223** [comment]
수정완료했습니다!

확인부탁드려요
