### ISSUE TITLE
[BUG] Y축 값 잘림 현상

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/Report#2]
7월 16일 기준 "김성실" 의 데이터로 봤을 때 배뇨 일별 데이터의 Y축 맨 하단에 값이 잘린 것처럼 보입니다.
![버그3](https://user-images.githubusercontent.com/8017454/125871589-2ea6e0e2-0377-406c-a19a-ca556d72eb58.png)

**Comment by sayiovme** [comment]
y: {
            //padding:0,
        },

y축 Design 중 Padding:0 코드를 삭제하여 해결하였습니다. 

*디버그 및 리디자인 후 한꺼번에 공식 서버 반영할 예정입니다.
