### ISSUE TITLE
[BUG] 그래프의 레전드 높이 오류

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/Report#20]
황선영_심함 7,8주차 그래프 기준으로 말씀드리지만 딱 이 케이스에만 해당되는 것은 아닐 것 같습니다. 코드 상의 어떤 조건문에 부합한다면 이러한 케이스가 다른 그래프에서도 나올 수 있어보입니다.

일단은 배뇨활동의 주차별 데이터 그래프의 레전드 (우측 상단의 배뇨 횟수)가 다른 그래프와 달리 높이가 다른 것을 확인하였습니다. 수분 섭취, 배뇨, 배변 모든 페이지의 그래프들은 레전드가 그래프의 영역 밖으로 벗어나지 않지만 여기에서만 벗어난 것으로 보입니다.

![화면 캡처 2021-07-27 222051](https://user-images.githubusercontent.com/8017454/127161147-de88d938-f299-43cf-a796-418d632a5a27.png)

**Comment by sayiovme** [comment]
해당 그래프 레전드를 그릴 때 y 값을 잘못 넣은 것 때문입니다.
수정하였습니다.
*이후 서버 반영 예정

![image](https://user-images.githubusercontent.com/60974691/127243187-4e12a518-9d03-4750-8d26-7c1f5a485036.png)

**Comment by sayiovme** [comment]
레전드를 그릴 때 위치를 잘못 설정한 탓입니다.
디버그하였습니다.

![image](https://user-images.githubusercontent.com/60974691/127251843-09fb23da-947b-4f40-afe9-bf3711c9bfe9.png)
