### ISSUE TITLE
[BUG] PDF 내에 웹 페이지의 색 영역 미반영 현상

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/Report#21]
PDF 렌더링 쪽은 영찬학생 담당인 것 같은데 아니면 assign 변경 부탁합니다.
첫번째 사진은 'PDF로 저장' 을 하여 정상 저장한 PDF 파일 캡처화면이고 두번째 사진은 웹페이지 화면입니다.
'일별 데이터' '주차별 데이터' '시간대 별 평균 데이터' 의 하늘색 음영이 PDF 에는 반영되지 않고 있습니다.
확대를 해 보아도 아예 안 보입니다.

![수분](https://user-images.githubusercontent.com/8017454/127161626-8cc01aa3-6d70-40a5-9ce5-092fe1dc4146.png)
![수분_웹](https://user-images.githubusercontent.com/8017454/127161642-7c7d3533-8d25-452d-9dec-0cb58fda7efd.png)

**Comment by junhyungmoon** [comment]
색상만 반영 안되는 것이 아니라 아래와 같이 테두리 박스도 PDF 에 반영이 안됩니다.


![배변_pdf](https://user-images.githubusercontent.com/8017454/127162207-cf218dc1-a332-4cd7-8f20-3b39659a25ac.png)
![배변_웹](https://user-images.githubusercontent.com/8017454/127162211-8dd58956-194d-4952-a822-0a218a8434ef.png)

**Comment by KimYC1223** [comment]
아앗 이것은... PDF로 인쇄하실 때 배경 그래픽을 포함하셔야 합니다

![image](https://user-images.githubusercontent.com/40852277/127162579-aa37c393-8eb0-44cf-a50c-f4813d6a3899.png)

---

![image](https://user-images.githubusercontent.com/40852277/127163478-7457418c-2f97-4bc2-8f02-36abb179e976.png)
