### ISSUE TITLE
[Enhancement] 수분 섭취와 배뇨 페이지 내부에서 3개 그래프 간 line 차이

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/Report#22]
수분 섭취와 배뇨 페이지 각 화면 내에서 보면 3개의 그래프에서 line 을 표현하는 것이 차이가 납니다.
통일시키는 것이 좋겠습니다

'일별 데이터' 는 거의 보이지 않고 (PDF 로 엄청 확대해도 거의 보이지 않습니다.)
'주차별 데이터' 는 보이긴 하지만
'시간대별 평균 데이터' 가 가장 진합니다.

![수분](https://user-images.githubusercontent.com/8017454/127162462-d6e9e22b-315e-4f79-aa75-821b346cf3ba.png)
![소변](https://user-images.githubusercontent.com/8017454/127162465-ab77f1a7-8f94-44ff-8ed7-c2b4fc0c7361.png)

**Comment by sayiovme** [comment]
세 그래프의 Grid line opacity를 최대한 비슷한 수준으로 맞춰보았습니다.
*서버에 이후 반영 예정

![image](https://user-images.githubusercontent.com/60974691/127241670-c0c50697-41b7-4fed-9c36-646d0499e382.png)
