### ISSUE TITLE
[Enhancement] 그래프 타이틀 표현 수준 통일

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/Report#23]
<수분섭취>
일별 데이터
주차별 데이터 - 일일 평균 섭취량
시간대별 데이터

위 타이틀을 보면 주차별 데이터만 부가 설명이 있고 나머지는 있지 않습니다. 
데이터라는 모호한 단어를 안 쓰면 타이틀의 표현 수준을 통일할 수 있겠습니다.

**일별 섭취량
주차별 일일 평균 섭취량
시간대별 평균 섭취량**

마찬가지로 배뇨와 배변도 아래와 같이 수정 요청합니다.

<배뇨 활동>
일별 배뇨 횟수
주차별 일일 평균 배뇨 횟수
시간대별 평균 배뇨 횟수

<배변 활동>
일별 배변 횟수
주차별 누적 배변 횟수

**Comment by sayiovme** [comment]
세 페이지 전부 수정하였습니다.
* 이후 서버 반영 예정
![image](https://user-images.githubusercontent.com/60974691/127242838-2fe32096-25f4-4c9c-b0fa-c4caa0f0d982.png)
