### ISSUE TITLE
[BUG] 배변활동-누적데이터 그래프 레전드의 텍스트 정렬 오류

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/Report#24]
황선영_심함 데이터로 1~8주 레포트를 모두 봤는데,
수분 섭취, 배뇨, 배변 모든 그래프 중 배뇨활동의 누적데이터 그래프만 레전트의 텍스트가 정렬이 다른 것을 확인하였습니다.

모든 그래프 내에서 레전드 도형과 텍스트간 간격이 동일한데,
아래 사진처럼 이 그래프에서만 그 간격이 서로 다릅니다. (회색 도형과 총 배변 횟수 간격이 더 멀음)

![배변](https://user-images.githubusercontent.com/8017454/127169047-184f5e02-9989-4038-bbc0-8452a9e74003.png)

**Comment by sayiovme** [comment]
해결하였습니다.
*서버에 이후 반영 예정

![image](https://user-images.githubusercontent.com/60974691/127241169-c3c691d1-e1b7-48e6-9f29-aef153a19505.png)
