### ISSUE TITLE
[Enhancement] 주의사항의 내용을 메인 화면에서도 한번 노출시키면 어떨까요

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/Report#26]
솔직히 이 웹페이지를 사용하면서 주의사항을 눌러볼 의사선생님이 몇이나 되실까 생각됩니다.
저만해도 주의사항을 눌러볼 생각이 들지 않았습니다.

높은 확률로 pdf 를 저장할 때 옵션을 잘못 선택하거나 배경 이미지를 선택하지 않아서
제가 발견했던 여러 이슈들을 우리 연구팀에게 문의해 올 것으로 예상합니다.

따라서 아래 메인화면에서 한번 노출시키면 어떨까요.
조금이나마 효과가 있지 않을까 생각됩니다.
너무 크고 강조하면 메인화면이 정신 없으니까 지금 주의사항 버튼 누르면 나오는 정도면 충분할 것 같아요
메인 화면에 한번 노출하고, 기존의 버튼은 그대로 유지하면 될 것 같습니다

![화면 캡처 2021-07-28 153514](https://user-images.githubusercontent.com/8017454/127275712-0c290f55-15b5-4393-8930-e800b2bc1c4b.png)

**Comment by KimYC1223** [comment]
수정했습니다! 이제 index.html에서도 보입니다.

**Comment by junhyungmoon** [comment]
아 저는 버튼 안의 내용을 레포트작성 버튼 위쪽으로 보이게 하면 좋을것 같다고 말씀드린 것이었습니다!
레포트 작성 눌러서 들어간 다음에는 지금과 동일하게 버튼으로 두고요~

![화면 캡처 2021-07-29 165220](https://user-images.githubusercontent.com/8017454/127453415-bec34ae9-b8fd-43a6-acf2-1adcd873ffa7.png)

**Comment by KimYC1223** [comment]
![image](https://user-images.githubusercontent.com/40852277/127460884-8648282a-7391-4eb6-9a01-f0e47b587003.png)

이렇게 말씀하시는게 맞으시죠?

변경하였습니다! http://fluidtrack.site:8055/
