### ISSUE TITLE
[BUG] 팀명이 버튼을 가리는 현상

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/Report#27]
아래 화면의 빨간 화살표로 가리킨 것처럼 저 문구가 버튼의 일부를 가려서 잘못 누르면 바로 github 페이지로 넘어가게 됩니다.

![화면 캡처 2021-07-29 123003](https://user-images.githubusercontent.com/8017454/127427236-c076fe00-8165-43b4-b384-2169cf6f1161.png)

**Comment by KimYC1223** [comment]
아 100%일땐 괜찮은데 확대를 하신거군요... 알겠습니다 확인했습니다

**Comment by junhyungmoon** [comment]
정확히는 리포트를 제가 보기 편한 정도로 확대한 상태에서 본 것이고, (아래 사진: 200%)
이 확대 배율이 크롬을 종료했다 꺼도 남아있어서 로그인 화면이 확대되어 있었네요. (다른 페이지가 아닌, 리포트 웹 페이지에서만 해당)
별로 중요한 것이 아닌데, 시간 오래 쓰는 것보다 그냥 팀명 지워도 됩니다.

![KakaoTalk_20210729_151128914](https://user-images.githubusercontent.com/8017454/127441242-6e717499-dcde-4048-aa36-0255e2f5213b.jpg)

**Comment by KimYC1223** [comment]
처리했습니다!
