### ISSUE TITLE
[BUG] 배뇨 일일 데이터 최솟값 표시 부재

### ISSUE THREAD

**Issue by 2sukhyunlee** [FluidTrack/Report#28]
일별 배뇨 횟수에서 최댓값은 표시가 되는데 최솟값은 표시되지 않습니다.

수분에서는 둘 다 표시가 되고 있어서 배뇨도 마찬가지로 최솟값 표시가 되어야 좋을 것 같습니다.

**Comment by 2sukhyunlee** [comment]
유저마다 배뇨활동 - 일별 데이터의 최소값 표기 여부가 달라지는 것 같습니다.
70번 유저는 최소값 표기가 없었는데, '김성실' 유저는 최소값이 표기됩니다.

**Comment by 2sukhyunlee** [comment]
> 유저마다 배뇨활동 - 일별 데이터의 최소값 표기 여부가 달라지는 것 같습니다.
> 70번 유저는 최소값 표기가 없었는데, '김성실' 유저는 최소값이 표기됩니다.

#37 이슈를 참고해주세요.

**Comment by sayiovme** [comment]
최솟값 표기를 완료하였습니다.
