### ISSUE TITLE
[BUG] 정상배뇨 횟수 표기 변경 현상

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/Report#29]
맨처음 의사선생님이 100% 배율인 상태로 접속했다고 가정해보겠습니다.
그 상태에서 리포트를 생성하시고 보다가 확대를 할 경우,
아래와 같이 정상배뇨 범주에 속하는 값이 초록색 글씨로 표기되어있다가 노란색 글씨로 바뀝니다.

![정상배뇨횟수](https://user-images.githubusercontent.com/8017454/127444217-2bcc267a-44e9-418e-a7aa-50adb5c5bdc5.png)

**Comment by sayiovme** [comment]
색깔 변경 jquery를 onrendered() 함수 안에 넣으며 해결하였습니다.

*이후 서버 반영 예정
