### ISSUE TITLE
[BUG] 그래프 속 아이콘과 레전드 불일치 현상

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/Report#3]
그래프 속에는 동그라미로, 우측 상단의 레전드에는 네모로 표기되어 있습니다.

![버그1](https://user-images.githubusercontent.com/8017454/125871783-a625fe44-b580-4513-88f8-988dcaa97f87.png)

**Comment by sayiovme** [comment]
1, 2, 3페이지 모두 circle로 일치하도록 리디자인 하였습니다.

*추후 공식 서버에 반영 예정
