### ISSUE TITLE
[BUG] 그래프 내에서 데이터 가운데 정렬 요청

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/Report#30]
이 그래프만 데이터가 가운데 정렬이 안 되어 있습니다.

![화면 캡처 2021-07-29 154335](https://user-images.githubusercontent.com/8017454/127444485-7cc8b924-bfa5-47ac-9b12-50a98555d467.png)

**Comment by sayiovme** [comment]
![image](https://user-images.githubusercontent.com/60974691/127452017-48e15bd7-27b4-4b0a-92c9-4919aa9250f7.png)

x값을 옮겨 디버그 하였습니다.
단 300%까지 확대하면 X축이 동적으로 늘어나면서 대변 아이콘 위치가 어긋나는 현상을 발견했는데요.
이 문제도 디버그하도록 하겠습니다. 

*이후 서버 반영 예정
