### ISSUE TITLE
[Enhancement] 정상배뇨범위의 주차별 그래프 추가 반영 요청

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/Report#31]
주차별 그래프에도 동일하게 정상범위를 표시해주면 좋을 것 같습니다.

![화면 캡처 2021-07-29 160322](https://user-images.githubusercontent.com/8017454/127446982-83a578e5-a517-424a-86cf-992c93a41321.png)

**Comment by 2sukhyunlee** [comment]
그럼 수분섭취의 주차별 데이터도 목표 섭취량 1000 ml를 표시하는 것으로 수정해야할까요?

**Comment by junhyungmoon** [comment]
네 그려주면 좋을 것 같습니다

**Comment by sayiovme** [comment]
둘 다 구현하였습니다.
