### ISSUE TITLE
[BUG] 시간대별 그래프에서 data와 legend의 bubble 사이즈 불일치

### ISSUE THREAD

**Issue by 2sukhyunlee** [FluidTrack/Report#32]
![image](https://user-images.githubusercontent.com/65483592/127452089-4f6302a9-bf6f-41a3-9f00-93906d28edbd.png)

수분, 배뇨활동에서 시간대별 그래프의 data bubble과 legend bubble 사이즈가 일치하지 않는 것 같습니다.
밤 8시가 36ml 인데 50ml legend와 비슷해보이고, 점심 12시가 79ml 인데 100ml legend와 비슷해보입니다.

![image](https://user-images.githubusercontent.com/65483592/127452878-82b35071-1acb-42c9-a764-00199b388d51.png)

소변도 그래프 상의 1회가 legend 1회보다 조금 커보입니다.

혹시 legend bubble의 크기가 항상 고정되어 있다면 데이터에 맞게 가변적이어야 할 것 같습니다.

**Comment by junhyungmoon** [comment]
이게 아마 선영학생이 소숫점 2자리였던 것을 아예 없앨지 1자리만 남길지 고민하다가 소숫점을 안 하기로 하여서 그런것 같습니다. 레전드가 소숫점 1자리 단위이니 소숫점 1자리까지는 표시해볼까요?

**Comment by 2sukhyunlee** [comment]
두 방안 중 하나를 선택하면 될 것 같습니다.
1. 지금처럼 소수점을 버리는 대신에 배뇨 1회라면 legend 1회와 동일한 사이즈로 맞추기
2. 소수점 첫째자리까지 나타내기. (legend 사이즈를 고려하지 않아도 됨)

말씀처럼 저도 2번이 좀 더 정확한 데이터를 알 수 있어 좋아보이는데 혹시 최근 미팅에서 소수점까지 나타냈다가 소수점은 버리자는 피드백이 있었던가요..?

그리고 수분은 소수점의 문제인 것 같지는 않기 때문에 소변과는 별개로 legend 사이즈와 맞출 필요가 있어보입니다..

**Comment by junhyungmoon** [comment]
지난번 이경우교수님께서 전원 소집한 회의에서 교수님께서 소숫점 2자리는 너무 과하다 하셨습니다. 저도 동의하고요

**Comment by 2sukhyunlee** [comment]
네 그렇다면 소수점 1자리까지는 좋아보입니다.

**Comment by sayiovme** [comment]
Legend bubble 크기는 가변적입니다만, 그리는 과정에서 실제보다 작게 그려진 것 같습니다.
원래 크기에 1.25배를 곱해 최대한 흡사하게 만들어보았습니다.

+

"시간대별 평균 횟수"에 한해 소변 횟수를 소숫점 1자리까지 드러내는 것으로 바꾸었습니다.
주간 평균 횟수는, 바로 위에 있는 일별 횟수가 자연수 그래프기 때문에 비슷한 방식으로 표현하는 것이 좋을 것 같아 소숫점을 버렸습니다. 

*추후 서버 반영 예정

**Comment by junhyungmoon** [comment]
bubble 로 그리지 않기로 하였으므로 close
