### ISSUE TITLE
[BUG] 수분 섭취 주차별 데이터의 표식 레이블 기준 마련

### ISSUE THREAD

**Issue by 2sukhyunlee** [FluidTrack/Report#35]
수분 섭취 - 주차별 데이터에서 물 표식에 대한 레이블은 일반적으로 표식 하단에 표기합니다.
하지만 값이 0에 가까울 경우 표식 하단에 레이블 표기하기가 어렵습니다.

값이 0에 가까울 경우, 몇 회 이하일 때 표식 상단에 레이블을 표기하는지 기준을 마련해주세요.
(배변은 2회 이하일 때 표식 상단에 표기)

**Comment by sayiovme** [comment]
각 150ml 이하, 0회 이하인 것으로 정해두었습니다.
