### ISSUE TITLE
[BUG] 시간대별 데이터 Y축 최소범위 생성 기준 마련

### ISSUE THREAD

**Issue by 2sukhyunlee** [FluidTrack/Report#36]
시간대별 데이터 Y축 범위의 최소 범위를 설정해야 합니다. 

현재 최소 시간 범위는 3시간으로 설정되어 있으나, 
1. 기록된 시간이 1시간일 경우
2. 기록된 시간이 2시간일 경우

각각의 경우에 대해 시간대가 어떻게 생성되는지 기준이 부재합니다.
e.g. 10시에만 기록이 존재할 때, Y축 시간대는 9시, 10시, 11시로 생성.

**Comment by sayiovme** [comment]
![image](https://user-images.githubusercontent.com/60974691/129699879-87b117ee-1e16-4b5c-8d3d-f4e66426ada8.png)

현재 코드에 따르면 1시간의 기록만 있을 경우
동일한 사이즈의 그래프 내에, 1시간 범위의 시간대만 표시되도록 구현되어 있습니다.
