### ISSUE TITLE
[BUG] 배뇨 일별 데이터 - 정상범위 내 표식 레이블 삭제

### ISSUE THREAD

**Issue by 2sukhyunlee** [FluidTrack/Report#37]
![image](https://user-images.githubusercontent.com/65483592/127520198-cb46ffb4-5f68-4f88-b115-4ab10b301a6d.png)

배뇨활동 - 일별 데이터에서 표식 레이블은 최대값과 최소값에서만 나타내야 합니다. 
정상범위 내에 속했더라도 최대값/최소값이 아니라면 레이블을 표시하지 않아야 합니다.

**Comment by sayiovme** [comment]
해결하였습니다.
