### ISSUE TITLE
[BUG] 그래프의 각 점 위에 숫자 표기하는 것 오류

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/Report#39]
아래 건강한대변 그래프의 3만 점 아래에 숫자가 표기되어 있습니다.

![화면 캡처 2021-08-03 083635](https://user-images.githubusercontent.com/8017454/127937168-cf864fdf-f916-4373-8089-88ffe1a63e07.png)

**Comment by sayiovme** [comment]
![image](https://user-images.githubusercontent.com/60974691/128024060-4efee064-575e-4627-8966-01a8e7ec8f6e.png)
![image](https://user-images.githubusercontent.com/60974691/128024173-c51cd483-0808-49c6-8336-83fd97fc896b.png)

오류라기보다는, 물-음료 섭취 그래프처럼 총 대변 레이블은 위로 가도록, 정상 대변 레이블은 아래로 가도록 표기한 것입니다.
정상 대변 횟수가 N회 이하일 경우 레이블이 X축과 겹쳐 잘 보이지 않아, N회 이하일 경우에는 레이블이 위로 가도록 표기해두었습니다. (물-음료 섭취 그래프 또한 동일합니다.)

현재는 0회일 때만 레이블이 위로 가도록 구현해두었습니다.
이슈는 우선 클로즈하겠습니다!
