### ISSUE TITLE
[Enhancement] 시간을 표기하는 공간 크기를 동일하게 하기

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/Report#4]
1자리수의 시간(예: 아침 9시)을 표기할 때 앞에 0을 붙여주면 
모든 시간이 같은 너비(width)로 잘 정렬되어 보일 것 같습니다.
나아가 아침, 점심, 저녁 글자가 시작하는 왼쪽 line 도 딱 맞게 되고요

![버그2](https://user-images.githubusercontent.com/8017454/125871882-1d81d742-2196-4dcc-a577-ea58ec6b0736.png)

**Comment by junhyungmoon** [comment]
동그라미가 각 가로선의 중앙에 오도록 정렬해주세요

**Comment by sayiovme** [comment]
"1자리수의 시간(예: 아침 9시)을 표기할 때 앞에 0을 붙여주면" 이란 말씀은 오후 시간대도 13시, 14시처럼 변경하라는 뜻이신가요? 

Circle은 다시 Centering하였습니다. 
![image](https://user-images.githubusercontent.com/60974691/126852427-793bc96b-0ee6-44f2-8c13-ffbc981a3ca4.png)

**Comment by junhyungmoon** [comment]
만약 아침, 점심, 저녁 글씨는 왼쪽 정렬을 하고 시간들은 우측 정렬 할 수 있으면 시간을 표기할때 앞에 0을 붙여주지 않아도 보기에 깔끔할 것 같습니다.

처음 적었던 코멘트는 점심 01시, 02시, 03시 로 바꾸는 것을 의미했던 것입니다.

그리고 아래는 황선영_심함 7,8주 그래프인데, 아침, 점심, 저녁, 밤 모두 3시간 간격으로 표시되는데 점심과 저녁 사이에만 6시간 간격입니다. 낮이라고 중간에 넣어주면 어떨까요


![화면 캡처 2021-07-27 215300](https://user-images.githubusercontent.com/8017454/127156806-e9bd232b-e55a-4fc9-a919-eff55f7e7e4b.png)

**Comment by junhyungmoon** [comment]
@sayiovme 
이건, 시간 앞에 0을 붙이는건 하지 마시고, 대신 3시간 간격마다 동일하게 한글 표기는 맞춰주세요~
지금은 점심과 저녁 사이만 6시간이고 나머지는 3시간씩입니다. (아침~점심, 저녁~밤)

새벽 -> 아침 -> 점심 -> 낮 -> 저녁 -> 밤
