### ISSUE TITLE
[BUG] 대변 주차별 그래프 변경 요청

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/Report#40]
지난 금요일 회의에서 이 것은 누적 데이터로 하지 말자고 결정하였습니다.

![4](https://user-images.githubusercontent.com/8017454/127956788-d6706559-9d8a-4350-8437-885e4faa1c6e.png)

**Comment by sayiovme** [comment]
현재 "1주일치"의 누적 데이터만 보여지도록 만들어진 상태입니다.
추가로,
"주차별 배변 횟수"로 표기를 변경하였습니다. (서버 반영 이후 메일 발송 예정)
