### ISSUE TITLE
[Question] 녹색 글씨 삭제 여부

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/Report#41]
66번, 70번 데이터 모두 확인할 방법이 없어서 확인차 적어둡니다.

"""
- 노란 꺾은선 그래프 뒤로 녹색 음영을 보냄(지금은 녹색 음영이 앞으로 나와있음)
- 녹색 글씨 x
"""

![4](https://user-images.githubusercontent.com/8017454/127956930-10c9ed11-c4b2-4912-a777-50ddb2400872.png)

**Comment by sayiovme** [comment]
네, 둘 다 고쳐진 상태입니다.
66번 7, 8주차 데이터에서 확인하실 수 있습니다! 

![image](https://user-images.githubusercontent.com/60974691/128019476-0a12f604-c430-47ea-8d35-4bf8f1b74fc3.png)
