### ISSUE TITLE
[Enhancement] 횡방향 bar graph 중심축 이동 요청

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/Report#42]
bar 의 중심이 시간에 가도록 하는 것이 맞을것 같습니다. 
기존에 버블이 시간 grid 의 중심이었던 것과 동일하게 말입니다.

![4](https://user-images.githubusercontent.com/8017454/127957091-6228945c-6628-45f7-a39d-80936ee4b1d5.png)

**Comment by sayiovme** [comment]
중심축 이동시켰습니다.
![image](https://user-images.githubusercontent.com/60974691/128114252-01d0ac23-c164-41c4-9865-a103c0e54d05.png)
