### ISSUE TITLE
[BUG] 횡방향 점선 확장 누락

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/Report#43]
횡방향 점선을 더 길게 그려야합니다

![4](https://user-images.githubusercontent.com/8017454/127957203-9b510483-ce34-44e2-b42b-32afa83a4260.png)

**Comment by sayiovme** [comment]
![image](https://user-images.githubusercontent.com/60974691/128019324-9e66b27c-829a-4a5f-a737-3c5a2c2be6bd.png)
수정하였습니다.

*서버 반영 후 메일 드리겠습니다.
