### ISSUE TITLE
[BUG] 레이블 Bold 삭제 누락

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/Report#44]
Bold 를 다 잘 지워주셨는데, 남아있는 곳이 있습니다. 여기 뿐만 아니라 여러 그래프에요~

![4](https://user-images.githubusercontent.com/8017454/127957283-ebc2b7bf-543c-470b-91f4-e867f235720e.png)

**Comment by sayiovme** [comment]
![image](https://user-images.githubusercontent.com/60974691/128019227-a4b9a594-ff07-4ee6-a127-402cd982260b.png)
수정하였습니다.

*서버 반영 후 메일 드리겠습니다.
