### ISSUE TITLE
[Enhancement] 소숫점 반올림 안내 문구 개선 요청

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/Report#45]
(1) 지금 저 위치에 적으면, 주차별 그래프의 데이터만 반올림을 했다는 의미로 보입니다.
(2) 글씨가 뭉개져서 보입니다. 다른 글씨에 비해 선명도가 낮습니다.

![1](https://user-images.githubusercontent.com/8017454/127957458-4337c53d-82e5-41b4-8ab1-1a6724f3779a.png)

**Comment by sayiovme** [comment]
(1) 현재 주차별 그래프는 첫째자리, 시간대별 그래프는 둘째자리에서 반올림한 상황이라 저 위치에 놓았습니다. 
우선 시간대별 그래프에도 해당 문구를 추가해보겠습니다.

(2) 크롬에서 10px 미만 폰트를 지원하지 않아 이미지로 넣은 탓에 저렇게 보이는 것 같습니다.
우선 방법을 찾아보겠습니다.

**Comment by sayiovme** [comment]
![image](https://user-images.githubusercontent.com/60974691/128029633-ee14fceb-3376-421d-b20a-757a07feb657.png)

답변대로 수정해보았습니다. (시간대별 그래프에도 문구를 추가함, 이미지를 텍스트로 변경해서 더 이상 뭉개지지 않음)
추가로 의견 있으시면 언제든 Issue reopen 부탁드립니다.
