### ISSUE TITLE
[Enhancement] 하단 로고 이슈

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/Report#47]
월요일 미팅에서 교수님께서 로고를 지적하셨던게 기억나는데 자세한 내용은 영찬학생이 잘 알고 있을 것이라 생각됩니다.

**Comment by KimYC1223** [comment]
네, 안그래도 어제 관련해서 연락드리긴 했는데, 아직 답장이 없으시네요.

리마인드 겸 다시 한번 여쭤보겠습니다

**Comment by junhyungmoon** [comment]
수고하셨습니다
