### ISSUE TITLE
[Enhancement] 배뇨 그래프 bar 로 전환

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/Report#48]
지난 회의에서 배뇨 그래프는 왜 line 이냐는 이야기를 하다가 최종적으로 전부 bar 로 그리자고 정리된 것으로 기억합니다. 저는 회의록에 그렇게 썼는데 혹시 잘못 기억하는 것이면 댓글로 남겨주세요

**Comment by sayiovme** [comment]
저도 정확하게 기억하지는 못합니다만 이봉신 박사님이 한참동안 고민하시다가 그냥 넘어간 것으로 기억해 우선은 Line으로 표현하엿습니다. 저도 헷갈리네요 ㅜㅜ
