### ISSUE TITLE
[Enhancement] X,Y grid 통일 이슈

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/Report#49]
Grid line 을 X, Y 축 모두 실선으로 통일하는 것이 낫지 않을까 생각됩니다.

![화면 캡처 2021-08-10 170903](https://user-images.githubusercontent.com/8017454/128831846-0a9ffe36-9d5b-4c0a-b822-2edfb7dc00ac.png)

**Comment by sayiovme** [comment]
![image](https://user-images.githubusercontent.com/60974691/128835558-eb741dc2-61f2-4395-8a25-242ae5cb25ad.png)

그렇게 구현해보았습니다.
점선과 실선 중에서 더 나은 것 선택해주시면 서버 반영하겠습니다.

**Comment by junhyungmoon** [comment]
실선으로 통일하는 것이 나을 것 같습니다.
