### ISSUE TITLE
[BUG] 커서 위치와 표시되는 데이터 불일치

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/Report#5]
캡처를 해도 마우스 커서는 캡처가 안되네요..
아래 2개 사진은 시간대별 평균 데이터에서 11시 동그라미에 마우스 커서를 가져갔을때 표시되는 데이터입니다.
10시와 12시의 데이터가 나오고 있습니다. 
마우스 커서를 미묘하게 위 아래로 아주 조금만 움직여도 10시와 12시의 데이터가 나오고 11시의 데이터는 나오게 하기 힘드네요...
화면 배율 100%인 상태에서 테스트 한 것입니다.

![에러1](https://user-images.githubusercontent.com/8017454/126731231-3a7e38d1-7db3-453d-8a2b-9bf3457bfd53.png)
![에러2](https://user-images.githubusercontent.com/8017454/126731232-d316df6a-a6e4-4ded-8a7b-87b252981f0a.png)

**Comment by sayiovme** [comment]
본래 Circle이 일렬로 정렬되어있지 않은 Scatter plot 그래프를 정렬하다보니 발생한 현상인데요.
따라서 적은 값의 데이터일 경우 Y축 시작부분에 커서를 움직여야 Tooltip이 뜨는 식의 버그입니다.
 
커서를 Circle 위치로 움직였을 때 tooltip이 뜨도록 디버그하려는 예정입니다
우선 최선을 다해보겠습니다

**Comment by junhyungmoon** [comment]
오늘 버전에서 황선영_심함 7,8주차 레포트 기준으로 말씀드립니다.
배뇨 데이터에는 동그라미에 커서를 가져갔을 때 아예 값이 보이지 않는 것 같습니다. 아직 완료된 이슈가 아니므로 수정중이겠지만, 혹시 놓칠까봐 알려드립니다.

**Comment by junhyungmoon** [comment]
interactive 기능 삭제에 따라 closed
