### ISSUE TITLE
[BUG] 대변 그래프 Y축 오류

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/Report#50]
빨간 동그라미 표기 부분 오류입니다 (66번, 1~2주차 그래프)

![화면 캡처 2021-08-10 171132](https://user-images.githubusercontent.com/8017454/128832118-1d8705aa-97eb-45a1-80ea-60117659a654.png)

**Comment by sayiovme** [comment]
![image](https://user-images.githubusercontent.com/60974691/128832334-d9d070a6-d127-4df8-b4ba-889ff6444caa.png)

발견하여 즉각 수정했습니다.
다른 피드백 디버깅한 후 서버에 추후 반영하겠습니다.
