### ISSUE TITLE
[BUG] 대변 그래프 값 표기 오류

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/Report#51]
우측 막대기에 값이 표기 누락되었습니다

![화면 캡처 2021-08-10 171252](https://user-images.githubusercontent.com/8017454/128832306-1f723853-a55a-49ca-a9de-9286a65fe5f9.png)

**Comment by sayiovme** [comment]
![image](https://user-images.githubusercontent.com/60974691/128832447-275baa15-d95e-4984-865e-d4dc2b6c22ae.png)

마찬가지로 즉각 수정하였습니다.
다른 피드백 디버깅한 후 추후 서버에 반영하겠습니다.
