### ISSUE TITLE
[BUG] 대변 그래프 레전드 높이

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/Report#52]
아래 그래프만 한 페이지 내에서 위/아래 그래프의 레전도 높이가 다른것 같습니다

![화면 캡처 2021-08-10 171444](https://user-images.githubusercontent.com/8017454/128833414-26906f74-64a3-4285-9111-147ac4af8143.png)

**Comment by sayiovme** [comment]
![image](https://user-images.githubusercontent.com/60974691/128833568-4d570d6e-b3a3-43b7-a805-9056f95bb473.png)

이것도 대변 그래프 이슈를 수정하면서 해결되었습니다.
혹시 다른 데이터에서 이런 이슈가 발견된다면 언제든 리오픈 부탁드립니다.

*다른 피드백 포함 디버깅 후 서버 반영 예정
