### ISSUE TITLE
[Enhancement] 시간 레전드 개선 요청

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/Report#53]
#4 <- 이 것의 댓글로 썼던건데, 해당 이슈는 다른 내용이 섞여 있으니 close 하고 여기에서 따로 말씀드립니다

6시 새벽 (or 아침)
9시 아침 (or 오전)
12시 점심
3시 낮 (or 오후)
6시 저녁
9시 밤

이렇게 3시간마다 같은 간격으로 표시해주는 것이 데이터를 설명할 때도 좋을 것 같습니다.
괄호 안의 것이 더 낫다면 3개 "모두" 괄호 안의 것으로,
괄호 밖의 것이 더 낫다면 3개 "모두" 괄호 밖의 것으로 하는 것이 좋을 것 같습니다.

![화면 캡처 2021-08-10 171817](https://user-images.githubusercontent.com/8017454/128833705-ce3c726e-cdd0-4df0-b7ba-8c37c4ac197f.png)

**Comment by sayiovme** [comment]
네, 이 이슈도 오늘 중으로 수정하겠습니다!

**Comment by sayiovme** [comment]
![image](https://user-images.githubusercontent.com/60974691/128837036-96e1470d-22a1-44b1-bf7d-f6b1bce3c67e.png)

새벽 3시
새벽 6시
아침 9시
점심 12시
낮 3시
저녁 6시
밤 9시
밤 12시

이렇게 표기하였습니다.
혹시 수정사항이 있으면 리오픈 부탁드립니다.

*추후 서버 반영 예정
