### ISSUE TITLE
[Enhancement] 빨간색으로 표시된 날짜에 대한 설명

### ISSUE THREAD

**Issue by Yeohyun00** [FluidTrack/Report#54]
사용자들이 어떤 날짜는 빨간색으로 표시되어있는 것을 이상하게 느낄 수 있을거라 생각합니다.
일별 그래프 하단 혹은 레포트 최상단의 '이 레포트는 ~ 제작되었습니다.' 밑에
주말은 빨간색으로 표시하였다는 설명을 추가하면 좋을 것 같습니다.

**Comment by Yeohyun00** [comment]
이상하게 우측의 assignees 와 labels 추가가 안되어서 멘션하겠습니다..ㅎㅎ
@sayiovme

**Comment by sayiovme** [comment]
![image](https://user-images.githubusercontent.com/60974691/128851313-a54b8681-e28b-4b61-bfff-a34fe983aca6.png)
우선 이런 식으로 문구를 넣어보았습니다.
폰트 사이즈 / 위치 등에 있어 의견이 있으면 언제든 댓글 주세요.

**Comment by Yeohyun00** [comment]
> ![image](https://user-images.githubusercontent.com/60974691/128851313-a54b8681-e28b-4b61-bfff-a34fe983aca6.png)
> 우선 이런 식으로 문구를 넣어보았습니다.
> 폰트 사이즈 / 위치 등에 있어 의견이 있으면 언제든 댓글 주세요.

저는 만족합니다! 감사합니다.
