### ISSUE TITLE
[BUG] opacity 불일치

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/Report#55]
동그라미 표시하였습니다

![화면 캡처 2021-08-10 234854](https://user-images.githubusercontent.com/8017454/128888780-da6692a2-9022-402c-8d81-f1aaebb163bf.png)

**Comment by sayiovme** [comment]
![image](https://user-images.githubusercontent.com/60974691/129695448-2946abec-f933-4d89-9d9c-968038ac26b5.png)

현재 제 컴퓨터에서는 차이 없기 보입니다. 가끔 일어나는 현상일 수도 있을 것 같습니다.
우선 원인을 파악해보겠습니다만 혹시 또 발생한다면 보고해주세요.
