### ISSUE TITLE
[BUG] 성별 오류

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/Report#57]
참가자 107번은 여아이고, DB에도 female 로 되어있는데 리포트에는 남 이라고 나옵니다
아이의 이름이 캡처되기 때문에 사진은 첨부하지 않습니다.

**Comment by sayiovme** [comment]
이 파트 또한 본래 영찬님이 구현해주셨던 부분인데요. 디자인 부분을 마치고 해당 파트를 재점검해보겠습니다. 감사합니다.
