### ISSUE TITLE
[BUG] 연령 일괄 5세 고정 현상

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/Report#58]
107번 아동은 만 4세인데, 만 5세라고 표기됩니다.
생일에 따라서 연령이 counting 되지 않는 것인가 예상합니다.

역시 개인 정보가 캡처되므로 사진은 첨부하지 않습니다.

**Comment by junhyungmoon** [comment]
제가 테스트하는 114번 데이터로 확인해보니 연령이 아예 5세로 고정된 것 같습니다.
2011년생도 만 5세로 나오네요

**Comment by sayiovme** [comment]
본 파트는 본래 영찬님이 구현해주신 부분인데요. 우선 디자인을 마치고 해당 오류를 재점검해보겠습니다. 감사합니다.
