### ISSUE TITLE
[BUG] 일별, 주차별 그래프 y방향 그리드선 안 보이는 현상

### ISSUE THREAD

**Issue by Yeohyun00** [FluidTrack/Report#59]
'66번' 어린이 '1-2주차'의 레포트 작성해보니,
아래 사진처럼 일별, 주차별 그래프의 y방향 그리드선이 보이지 않았습니다. 

<img width="464" alt="일별, 주차별 그래프 선 안보임_0812(66번 어린이 1-2주차)" src="https://user-images.githubusercontent.com/77374615/129133746-c180c5b1-9283-4fc8-a158-319932212e60.png">

새로고침하니 정상적으로 복구되긴 하였습니다.
@sayiovme

**Comment by sayiovme** [comment]
드물게 나타나는 현상이라 아직 debug를 못한 상태입니다. 다시 나타날 경우 보고 부탁드립니다.
