### ISSUE TITLE
[Enhancement] 최하단 로고 이슈

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/Report#6]
이경우교수님께서 말씀하셨던 이슈를 적어둡니다.
- 세브란스 어린이병원의 글씨 폰트가 부적절
- 우측 하단에 연세대학교 로고 삽입

**Comment by junhyungmoon** [comment]
오늘 어린이병원에 회의하러 갔다가 찍은 것입니다.
이 로고가 더 나아보이는데 바꿀 방법이 있는지 확인해보면 좋겠습니다.
이걸 사용하면 검정색으로 세브란스 어린이병원을 다시 쓸 필요도 없고
영어보다 폰트가 더 커 보입니다.

![개선2](https://user-images.githubusercontent.com/8017454/126753272-77dc173e-9cee-4ce7-a543-19b8c89a5650.jpg)

**Comment by KimYC1223** [comment]
말씀하신 로고의 원본은 찾지 못했고,

![image](https://user-images.githubusercontent.com/40852277/126762884-621eae14-508b-4231-9be3-710ed2ca3859.png)

포토샵으로 작업한 결과를 삽입하기로 했습니다.

연세대학교 로고는 아래 로고로 삽입하겠습니다.

![image](https://user-images.githubusercontent.com/40852277/126762943-bdf22b28-5568-43f6-ada6-cf26f80d2015.png)

**Comment by KimYC1223** [comment]
해결!
