### ISSUE TITLE
[Enhancement] 묽은 대변 세로 가운데 정렬

### ISSUE THREAD

**Issue by Yeohyun00** [FluidTrack/Report#60]
아래 사진처럼 2회에 있는 묽은 대변이 그 옆의 딱딱한 대변에 비해 살짝 위로 올라가있는 것 같습니다.

<img width="715" alt="묽은 대변 가운데 정렬 필요 new" src="https://user-images.githubusercontent.com/77374615/129134506-175148b1-b29b-475a-bdad-7f02b782a60c.png">

@sayiovme

**Comment by junhyungmoon** [comment]
정렬이 보여서 첨언하자면, 14일과 22일의 딱딱한 대변이 가운데가 아닌 우측 정렬 된 것처럼 보입니다

**Comment by sayiovme** [comment]
1~3px 내로 조정해보았습니다. 
![image](https://user-images.githubusercontent.com/60974691/129695243-84f1a0fa-b367-4000-80cd-13d8a7dfa1ff.png)
