### ISSUE TITLE
[Enhancement] 네자리수 데이터값이 있을 때 사이 띄우기

### ISSUE THREAD

**Issue by Yeohyun00** [FluidTrack/Report#61]
아래 사진처럼 극단적인 수치는 아니더라도,
1000ml 이상의 값은 나올 거라 생각합니다.
그렇다면 두 숫자가 아래와 같이 겹칠 것 같은데, 
네자리수 데이터값이 있을 때 좀 더 사이를 띄우도록 설정하면 좋을 것 같습니다.

<img width="529" alt="네자리수 데이터 자리겹침" src="https://user-images.githubusercontent.com/77374615/129136729-178f939f-c557-4d10-b551-d5eceac4e776.png">

@sayiovme

**Comment by sayiovme** [comment]
![image](https://user-images.githubusercontent.com/60974691/129697577-1638d439-f7b2-4319-86f2-f67666917737.png)

모든 label의 폰트 사이즈를 8px -> 7px로 줄여보았습니다.

**Comment by sayiovme** [comment]
![image](https://user-images.githubusercontent.com/60974691/129699002-5119b800-24e3-4f9b-b624-fb8b6581ab7d.png)

모든 data label의 font-size를 8px에서 6px로 낮춰 해결해보았습니다. 
label이 너무 작다고 여겨지시면 바 크기를 늘려 안 겹치도록 해보겠습니다.
