### ISSUE TITLE
[Enhancement] 최상단 리포트명 변경

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/Report#7]
FluidTrack 이라는 명칭이 아니라 figma 에서 정했던 최종 버전의 리포트 명으로 변경 요청

**Comment by junhyungmoon** [comment]
관련하여 상단에 "아동이 2주간~~" 이 안에도 fluidtrack 이 쓰여 있으니 모아밴드와 모아정원 어플리케이션으로 바꿔주세요

**Comment by junhyungmoon** [comment]
띄어쓰기 부탁합니다
![개선3](https://user-images.githubusercontent.com/8017454/126753794-3f4e8e03-023b-486c-980f-d1494eb3f51b.png)

**Comment by KimYC1223** [comment]
해결!
