### ISSUE TITLE
[BUG] 새로고침을 1회 해야만 리포트가 보이는 현상

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/Report#8]
크롬에서 '김성실'을 입력하고 리포트 생성을 눌렀을 때 나오는 화면입니다.
매번 새로고침을 눌러야만 리포트가 나오는 것은 좋지 않은 것 같습니다.

![에러1](https://user-images.githubusercontent.com/8017454/126752652-3cc8d276-d96a-471a-9c1a-680bf2d4a586.png)

**Comment by sayiovme** [comment]
우선 기존 버그 중 하나였던, resize를 할 경우 Water Daily Graph와 Pee Daily Graph의 Y2축 Label이 삭제되는 현상은 수정하였습니다.
![image](https://user-images.githubusercontent.com/60974691/126867537-2a98ae90-f2f3-407e-b01c-a78e534b478d.png)

라벨 잘림 방지용 코드와 충돌한 것으로 판단됩니다.
    setTimeout(function(){

            
        let temp=$(".P2_weeklyGraphDiv").find(".bb-main")
        let $elem1=$(".P2_weeklyGraph").find(".bb-chart-texts").clone().appendTo(temp);
        let $elem2=$(".P2_weeklyGraph").find(".bb-ygrid-lines").clone().appendTo(temp);

    })


새로고침 해야 그래프가 보이는 현상은 제 컴퓨터에선 매우 드물게 일어나는 일이라 우선 테스트를 좀 해보아야 할 것 같습니다.
