### ISSUE TITLE
[Enhancement] PDF 출력시 여백 줄이기

### ISSUE THREAD

**Issue by junhyungmoon** [FluidTrack/Report#9]
PDF 로 변환해보니 일반적으로 보아온 문서보다 상하좌우 여백이 넓은 것 같습니다.
여백을 줄이고 컨텐츠를 더 크게 보이게 하여 가독성을 높이는 것이 더 좋은 방향 같습니다.
![개선1](https://user-images.githubusercontent.com/8017454/126753525-eaf51325-8685-4647-8924-5449f6f1c763.png)

**Comment by KimYC1223** [comment]
![image](https://user-images.githubusercontent.com/40852277/126754465-3574805d-1a5a-4939-9eaa-4fd5276ea407.png)

저는 문제가 없이 정상적으로 잘 보이는데, 혹시 어떤 환경에서 PDF변환을 시도하셨는지 알 수 있을까요?

제가 시도한 환경은 Whale과 Chrome입니다.

## - Whale

![image](https://user-images.githubusercontent.com/40852277/126754696-89d7363a-493e-4cb7-ba50-51338d5d3891.png)

---

## - Chrome

![image](https://user-images.githubusercontent.com/40852277/126754811-fd45efea-3a51-422d-8e80-5029882f2be0.png)

**Comment by KimYC1223** [comment]
#12와 같은 원인으로 판단되었습니다. 이슈 클로즈!!!
